class PrimaryKey:
    """Marks a column as a primary key"""

    ...


class AutoGenerated:
    """Marks a column as auto-generated"""

    ...


class AutoIncrement:
    """Marks a column as auto-increment"""

    ...


class Unique:
    """Marks a column as unique"""

    ...


class CheckTypes:
    """Controls type checking for this column"""

    def __init__(self, enabled: bool = True):
        self.enabled: bool = enabled


class Default[T]:
    """Sets a default value for a column"""

    def __init__(self, value: T):
        self.value: T = value


class NotNull:
    """Marks a column as not-null"""

    ...
