from .column import Column


class ForeignKey[T](Column[T]):
    def __init__(
        self,
        referenced_column:str,
        column_name:str,
        column_value:T,
        *,
        is_autogenerated=False,
        is_unique=False,
    ) -> None:
        super().__init__(
            column_name,
            column_value,
            is_primary_key=False,
            is_autogenerated=is_autogenerated,
            is_auto_increment=False,
            is_unique=is_unique,
        )
        self._referenced_column = referenced_column
        pass
