from typing import Annotated
from ormlambda import (
    Column,
    Table,
)

from datetime import datetime
from ormlambda.dialects.mysql import DATETIME, INTEGER
from ormlambda import Default, PrimaryKey, AutoIncrement


class TableWithAutoGenerated(Table):
    __table_name__ = "__test_table__AUTOGENERATED"

    Col_pk_auto_increment: Annotated[Column[int], INTEGER(), PrimaryKey(), AutoIncrement()]
    Col_auto_generated: Annotated[Column[datetime], DATETIME(), Default("CURRENT_TIMESTAMP")]
    Col3: Column[int]
    Col4: Column[int]
