from typing import Annotated
from ormlambda import (
    Column,
    Table,
)

from datetime import datetime
from ormlambda.types import Default, PrimaryKey, AutoIncrement, DateTime, Integer


class TableWithAutoGenerated(Table):
    __table_name__ = "__test_table__AUTOGENERATED"

    Col_pk_auto_increment: Annotated[Column[int], Integer(autoincrement=True), PrimaryKey()]
    Col_auto_generated: Annotated[Column[datetime], DateTime(), Default("CURRENT_TIMESTAMP")]
    Col3: Column[int]
    Col4: Column[int]
