import abc


class IDatabaseConnection[TCnx](abc.ABC):
    @abc.abstractmethod
    def cursor(self, **kwargs): ...
    @abc.abstractmethod
    def commit(self): ...
    @abc.abstractmethod
    def rollback(self): ...
    @abc.abstractmethod
    def get_connection(self) -> TCnx: ...
