class ColumnInfo:
    def __init__(
        self,
        column_name,
        column_value,
        *,
        is_primary_key=False,
        is_autogenerated=False,
        is_auto_increment=False,
        is_unique=False,
    ) -> None:
        self.column_name = column_name
        self.column_value = column_value
        self.primary_key = is_primary_key
        self.auto_generated = is_autogenerated
        self.auto_increment = is_auto_increment
        self.is_unique = is_unique

    def __repr__(self) -> str:
        return f"<Column: {self.column_name}>"
