name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    strategy:
      fail-fast: false
      
    steps:
    # Step 1: Check out the code from your repository
    - name: Check out code
      uses: actions/checkout@v3

    - name: Execute SQL script
      run: |
        mysql -h127.0.0.1 -uroot -proot testdb < /src/test/schema/sakila-db.sql

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 4: Install dependencies (if needed)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with test

    # Step 5: Set PYTHONPATH to include src
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    # Step 6: Run the tests using Poetry
    - name: Run tests
      run: poetry run python src/test/test_queries/test_select.py
